# md_class: 
#   heading:    sg-heading
#   hr:         sg-hr
#   link:       sg-link
#   image:      sg-img
#   paragraph:  sg-p
#   list:       sg-list
#   listitem:   sg-list__item
#   table:      sg-table
#   tablerow:   sg-table__row
#   tablecell:  sg-table__cell
#   blockquote: sg-blockquote


# Aigis will run from same directory where this config file resides
# All paths should be relative to there
name: CodeCrid CSS Style Guide

# The directory containing the source files to parse recursively
source:
  - ./src/assets2/scss
# You may alternately specify multiple directories
# source:
#  - ./sass
#  - ./sass/style.scss

# The types that aigis will scan to document comment
source_type:
  - .css
  - .scss
# If you want to generate documents from markdown
# source_type: .md

# The directory that aigis will build to
dest: ./build/styleguide

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./src/aigis-template/aigis_assets

# Index page created from markdown file
index: ./README.md

# You can choose template engine : ejs, jade, handlebars
template_engine: hbs

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./src/aigis-template/template_hbs

# Aigis displays logs
log: true

# When you don't want color palette page (color.html) you may set false
color_palette: true

#
transform:
  - html
  - jade
  - js
  - coffee

# Aigis
timestamp_format: 'YYYY/MM/DD HH:mm'

preview_class: aigis-preview

component_dir: ./html

output_collection:
  - category
  - tag

highlight: true
highlight_theme: okadia

# plugin directory
# plugin: ./plugin

helper_options:
  disable_link_index: true