version: 2
jobs:
  build:
    working_directory: /workspace
    docker:
      - image: node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - deploy:
          name: Deploying to S3 (on master only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            else
              echo "do nothing ;D"
            fi
