version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  test-setup:
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: npm ci
  deploy:
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: s3://ui.codegrid.net
          arguments: --delete --acl public-read

workflows:
  version: 2
  test:
    jobs:
      - test-setup
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
