version: 2.1

jobs:
  test-setup:
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: npm ci
  deploy:
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: npm ci
      - deploy:
          name: Deploying to S3
          command: npm run deploy

workflows:
  version: 2
  test:
    jobs:
      - test-setup
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
